import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '../globals.css'
import {ClerkProvider} from "@clerk/nextjs";
import {redirect} from "next/navigation";
import ThemeProvider from "@/components/context/ThemeContext";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Smart Tool For Children',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    if (process.env.MAINTENANCE) {
        return redirect("/maintenance")
    }

    return (
        <ThemeProvider>
            <ClerkProvider>
                <html lang="en">
                <body className={inter.className}>

                {children}
                </body>

                </html>
            </ClerkProvider>
        </ThemeProvider>
    )
}
